releaseType: java-yoshi
handleGHRelease: true
extraFiles: [".cloudbuild/cloudbuild.yaml", ".cloudbuild/cloudbuild-test.yaml"]
branches:
- bumpMinorPreMajor: true
  handleGHRelease: true
  releaseType: java-yoshi
  branch: java7
