releaseType: java-yoshi
handleGHRelease: true
extraFiles: [".cloudbuild/cloudbuild.yaml", ".cloudbuild/cloudbuild-test-a.yaml", ".cloudbuild/cloudbuild-test-b.yaml", ".cloudbuild/cloudbuild-test-c.yaml" ]
branches:
- bumpMinorPreMajor: true
  handleGHRelease: true
  releaseType: java-yoshi
  branch: java7
