releaseType: java-yoshi
handleGHRelease: true
extraFiles:
  - .cloudbuild/cloudbuild.yaml
  - .cloudbuild/cloudbuild-test-a.yaml
  - .cloudbuild/cloudbuild-test-b.yaml
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
  - releaseType: java-backport
    handleGHRelease: true
    extraFiles:
      - .cloudbuild/cloudbuild.yaml
      - .cloudbuild/cloudbuild-test-a.yaml
      - .cloudbuild/cloudbuild-test-b.yaml
    branch: bump-minor-v-for-LTS
