rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - dependencies (11, java-bigquery)
      - dependencies (11, java-spanner)
      - dependencies (11, java-storage)
      - dependencies (11, java-pubsub)
      - flatten-plugin-check
      - build (8, java-bigquery, test)
      - build (8, java-bigquery, lint)
      - build (8, java-bigquery, clirr)
      - build (8, java-bigtable, javadoc)
      - build (11, java-bigquery, test)
      - build (11, java-bigquery, lint)
      - build (11, java-bigquery, clirr)
      - build (11, java-bigtable, javadoc)
      - javadoc-with-doclet (java-bigtable)
      - cla/google
      - graalvm-presubmit-shared-config-a (java-graalvm-ci-prod)
      - graalvm-presubmit-shared-config-b (java-graalvm-ci-prod)
  - pattern: java7
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
  - pattern: 1.13.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - dependencies (11, java-bigquery)
      - dependencies (11, java-spanner)
      - dependencies (11, java-storage)
      - dependencies (11, java-pubsub)
      - flatten-plugin-check
      - build (8, java-bigquery, test)
      - build (8, java-bigquery, lint)
      - build (8, java-bigquery, clirr)
      - build (8, java-bigtable, javadoc)
      - build (11, java-bigquery, test)
      - build (11, java-bigquery, lint)
      - build (11, java-bigquery, clirr)
      - build (11, java-bigtable, javadoc)
      - javadoc-with-doclet (java-bigtable)
      - cla/google
      - graalvm-presubmit-shared-config-a (java-graalvm-ci-prod)
      - graalvm-presubmit-shared-config-b (java-graalvm-ci-prod)
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-java-admins
    permission: admin
  - team: yoshi-java
    permission: push
