# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2 hours
substitutions:
  _JAVA_SHARED_CONFIG_VERSION: '1.7.2-SNAPSHOT' # {x-version-update:google-cloud-shared-config:current}
  _GRAALVM_B: 'graalvm22_3_jdk17'

steps:
  # GraalVM B build
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/cloud-devrel-public-resources/graalvm_b:${_JAVA_SHARED_CONFIG_VERSION}", "--file", "${_GRAALVM_B}.Dockerfile", "."]
    dir: .cloudbuild
    id: graalvm-b-build
    waitFor: ["-"]
  - name: gcr.io/gcp-runtimes/structure_test
    args:
      ["-i", "gcr.io/cloud-devrel-public-resources/graalvm_b:${_JAVA_SHARED_CONFIG_VERSION}", "--config", ".cloudbuild/${_GRAALVM_B}.yaml", "-v"]
    waitFor: ["graalvm-b-build"]
  - name: gcr.io/cloud-devrel-public-resources/graalvm_b:${_JAVA_SHARED_CONFIG_VERSION}
    entrypoint: bash
    args: [ './.kokoro/presubmit/downstream-build.sh' ]
    waitFor: [ "graalvm-b-build" ]