# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2 hours
substitutions:
  _JAVA_SHARED_CONFIG_VERSION: '1.15.3-SNAPSHOT' # {x-version-update:google-cloud-shared-config:current}
  _IMAGE_REPOSITORY: us-docker.pkg.dev/java-graalvm-ci-prod/graalvm-integration-testing
  _COMMIT_HASH_TAG: infrastructure-public-image-$SHORT_SHA
steps:
  # GraalVM A build
  - name: gcr.io/cloud-builders/docker
    args: ["build",
           "-t", "${_IMAGE_REPOSITORY}/graalvm_a:${_JAVA_SHARED_CONFIG_VERSION}",
           "-t", "${_IMAGE_REPOSITORY}/graalvm_a:${_COMMIT_HASH_TAG}",
           "--file", "graalvm-a.Dockerfile", "."]
    dir: .cloudbuild
    id: graalvm-a-build
    waitFor: ["-"]
  - name: gcr.io/gcp-runtimes/structure_test
    args:
      ["-i", "${_IMAGE_REPOSITORY}/graalvm_a:${_JAVA_SHARED_CONFIG_VERSION}", "--config", ".cloudbuild/graalvm-a.yaml", "-v"]
    waitFor: ["graalvm-a-build"]

  # GraalVM B build
  - name: gcr.io/cloud-builders/docker
    args: [ "build", "-t", "${_IMAGE_REPOSITORY}/graalvm_b:${_JAVA_SHARED_CONFIG_VERSION}",
            "-t", "${_IMAGE_REPOSITORY}/graalvm_b:${_COMMIT_HASH_TAG}",
            "--file", "graalvm-b.Dockerfile", "." ]
    dir: .cloudbuild
    id: graalvm-b-build
    waitFor: [ "-" ]
  - name: gcr.io/gcp-runtimes/structure_test
    args:
      [ "-i", "${_IMAGE_REPOSITORY}/graalvm_b:${_JAVA_SHARED_CONFIG_VERSION}", "--config", ".cloudbuild/graalvm-b.yaml", "-v" ]
    waitFor: [ "graalvm-b-build" ]

  # GraalVM C build
  - name: gcr.io/cloud-builders/docker
    args: [ "build", "-t", "${_IMAGE_REPOSITORY}/graalvm_c:${_JAVA_SHARED_CONFIG_VERSION}",
            "-t", "${_IMAGE_REPOSITORY}/graalvm_c:${_COMMIT_HASH_TAG}",
            "--file", "graalvm-c.Dockerfile", "." ]
    dir: .cloudbuild
    id: graalvm-c-build
    waitFor: [ "-" ]
  - name: gcr.io/gcp-runtimes/structure_test
    args:
      [ "-i", "${_IMAGE_REPOSITORY}/graalvm_c:${_JAVA_SHARED_CONFIG_VERSION}", "--config", ".cloudbuild/graalvm-c.yaml", "-v" ]
    waitFor: [ "graalvm-c-build" ]
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - ${_IMAGE_REPOSITORY}/graalvm_a:${_JAVA_SHARED_CONFIG_VERSION}
  - ${_IMAGE_REPOSITORY}/graalvm_b:${_JAVA_SHARED_CONFIG_VERSION}
  - ${_IMAGE_REPOSITORY}/graalvm_c:${_JAVA_SHARED_CONFIG_VERSION}
  - ${_IMAGE_REPOSITORY}/graalvm_a:${_COMMIT_HASH_TAG}
  - ${_IMAGE_REPOSITORY}/graalvm_b:${_COMMIT_HASH_TAG}
  - ${_IMAGE_REPOSITORY}/graalvm_c:${_COMMIT_HASH_TAG}
